<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-3GNVT0U" name="com.qa.testcases.EmployeeCreation" tests="3" failures="0" timestamp="09 Apr 2021 13:01:13 GMT" time="250.097" errors="1">
  <testcase name="endReport" time="15.054" classname="com.qa.testcases.EmployeeCreation">
    <error type="org.apache.commons.mail.EmailException" message="Cannot attach file &quot;./employee_report/Employee_report.html&quot;">
      <![CDATA[org.apache.commons.mail.EmailException: Cannot attach file "./employee_report/Employee_report.html"
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:333)
at com.qa.testcases.EmployeeCreation.send_email(EmployeeCreation.java:53)
at com.qa.testcases.EmployeeCreation.endReport(EmployeeCreation.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: "./employee_report/Employee_report.html" does not exist
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:322)
... 26 more
]]>
    </error>
  </testcase> <!-- endReport -->
  <testcase name="employee_validations" time="187.486" classname="com.qa.testcases.EmployeeCreation"/>
  <testcase name="update_bank_primary" time="47.557" classname="com.qa.testcases.EmployeeCreation"/>
</testsuite> <!-- com.qa.testcases.EmployeeCreation -->
